# Generated by Django 2.2.4 on 2019-10-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='Proyecto',
        ),
    ]
